controllers:
  prefix: /app
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

vuejs_app:
  path: /app/{vuejsRoute}
  defaults:
    {
      _controller: App\Controller\HomeController::index,
      vuejsRoute: "index.html",
    }
  requirements:
    vuejsRoute: ".*"
